# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echarts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Xb', models.CharField(max_length=20)),
                ('num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('author', models.CharField(default='wm-station', max_length=20)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
                ('industry', models.TextField()),
                ('area', models.TextField()),
                ('pe', models.TextField()),
                ('outstanding', models.TextField()),
                ('totals', models.TextField()),
                ('totalAssets', models.TextField()),
                ('liquidAssets', models.TextField()),
                ('fixedAssets', models.TextField()),
                ('reserved', models.TextField()),
                ('reservedPerShare', models.TextField()),
                ('pb', models.TextField()),
                ('date', models.TextField()),
                ('roe', models.TextField()),
                ('esp', models.TextField()),
                ('net_profits', models.TextField()),
                ('business_income', models.TextField()),
                ('net_profit_ratio', models.TextField()),
                ('gross_profit_rate', models.TextField()),
                ('arturnover', models.TextField()),
                ('inventory_turnover', models.TextField()),
                ('currentasset_turnover', models.TextField()),
                ('mbrg', models.TextField()),
                ('nprg', models.TextField()),
                ('nav', models.TextField()),
                ('targ', models.TextField()),
                ('epsg', models.TextField()),
                ('currentratio', models.TextField()),
                ('quickratio', models.TextField()),
                ('cashratio', models.TextField()),
                ('cf_sales', models.TextField()),
                ('rateofreturn', models.TextField()),
                ('cf_nm', models.TextField()),
                ('cf_liabilities', models.TextField()),
                ('cashflowratio', models.TextField()),
                ('epcf', models.TextField(default='wm-station')),
                ('bvps', models.TextField(default='wm-station')),
                ('bips', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
